using System.Collections.Generic;
using System.Linq;
using MobiusEditor.Headless;
using MobiusEditor.Model;
using Xunit;

namespace MobiusCore.Tests
{
    /// <summary>
    /// The Tiberian Factions build ships a mapeditor.json (generated by the mod repo's
    /// scripts/editor_manifest.py) that supplies every type the editor used to compile in.
    /// Full field-level parity with the old compiled tables was proven by this class's
    /// pre-cutover revision (git history); what remains pins the shipped manifest's shape,
    /// with the byte-exact save oracle as the behavioural net.
    /// </summary>
    public class ModManifestParityTests
    {
        private static ModManifest LoadManifest()
        {
            ModInfo mod = ModDiscovery.Read(TestPaths.ModDir);
            Assert.NotNull(mod);
            Assert.NotNull(mod.EditorManifestPath);
            List<string> warnings = new List<string>();
            ModManifest m = ModManifest.Load(mod.EditorManifestPath, mod.Name, warnings);
            Assert.NotNull(m);
            Assert.Empty(warnings);
            return m;
        }

        [Fact]
        public void TheTiberianFactionsBuildShipsAUsableManifest()
        {
            ModManifest m = LoadManifest();
            Assert.Equal("RA", m.GameType);
            Assert.Equal(50, m.Buildings.Count);
            Assert.Equal(7, m.Infantry.Count);
            Assert.True(m.Units.Count >= 28, $"only {m.Units.Count} units");
            Assert.True(m.Templates.Count >= 325, $"only {m.Templates.Count} templates");
            Assert.Contains(m.Units, u => u.Kind == ManifestUnitKind.Vehicle);
            Assert.Contains(m.Units, u => u.Kind == ManifestUnitKind.Aircraft);
            Assert.Contains(m.Units, u => u.Kind == ManifestUnitKind.Vessel);

            ManifestBuilding obelisk = m.Buildings.Single(b => b.Name == "tdobli");
            Assert.Equal(87, obelisk.Id);
            Assert.Equal("0 1", obelisk.OccupyMask);
            // The TS tree and the faction-split RA yards carry literal display names.
            ManifestBuilding tsWeap = m.Buildings.Single(b => b.Name == "tsweap");
            Assert.Equal(127, tsWeap.Id);
            Assert.Null(tsWeap.TextId);
            Assert.Equal("TS War Factory", tsWeap.DisplayName);
            Assert.Equal("tsweap2", tsWeap.FactoryOverlay);
            Assert.Equal("11110 11110 00000", tsWeap.OccupyMask);
            Assert.Equal(136, m.Buildings.Max(b => b.Id));
            ManifestTemplate sh1 = m.Templates.Single(t => t.Name == "tdsh1");
            Assert.Equal(401, sh1.Id);
            Assert.All(m.Templates, t => Assert.True(t.Id >= (int)TemplateType.TFTDTileIdFirst,
                $"{t.Name} is below the TF TD tile range"));

            // The factory accepts the whole file: every entry builds a real type.
            Assert.Equal(m.Buildings.Count, ModTypeFactory.Buildings(m).Count);
            Assert.Equal(m.Units.Count, ModTypeFactory.Units(m).Count);
            Assert.Equal(m.Infantry.Count, ModTypeFactory.Infantry(m).Count);
            Assert.Equal(m.Templates.Count, ModTypeFactory.Templates(m).Count);
        }
    }
}
